
#development:
#  adapter: postgresql
#  encoding: unicode
#  database: firstdeploy_development
#  pool: 5
#  username: firstdeploy
#  password:



development:
  adapter: postgresql
  username: postgres
  password: postgres
  encoding: SQL_ASCII
  template: template0
  database: firstdeploy_development
  encoding: utf8
  username: postgres
  password: postgres
  host: localhost
